import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { CustifyClient, CustifyApiError } from '../api/client.js';
import type { Note } from '../api/types.js';

function formatNote(n: Note) {
  return {
    id: n.id ?? null,
    text: n.text ?? null,
    entity_id: n.entity ?? null,
    entity_model: n.entityModel ?? null,
    entity_name: n.entityName ?? null,
    account_ids: n.company ?? [],
    contact_ids: n.people ?? [],
    tag_ids: n.tags ?? [],
    file_ids: n.files ?? [],
    sticky: n.sticky ?? false,
    status: n.status ?? null,
    show_in_portal: n.showInPortal ?? false,
    created_by: n.createdBy ?? null,
    created_by_type: n.createdByType ?? null,
    source: n.externalProvider ?? 'custify',
    external_id: n.externalId ?? null,
    created_at: n.created_at ?? null,
    updated_at: n.updated_at ?? null,
  };
}

export function registerNoteTools(server: McpServer, client: CustifyClient): void {
  // list_notes
  server.tool(
    'list_notes',
    `List Custify timeline notes, most recent first (sticky notes first when scoped to one account or contact). Note text is HTML. Notes include ones added manually by the CS team, generated by Playbooks, and imported from integrations (source field, e.g. "salesforce", "hubspot"). Scope with account_id or contact_id, or omit both to list notes across all accounts. Use create_note to add a new note.`,
    {
      account_id: z.string().optional().describe('Custify company/account ID — list notes on this account. Mutually exclusive with contact_id.'),
      contact_id: z.string().optional().describe('Custify contact (customer) ID — list notes on this contact. Mutually exclusive with account_id.'),
      limit: z.number().min(1).max(50).default(25).optional().describe('Number of results (1-50, default 25)'),
      offset: z.number().min(0).default(0).optional().describe('Pagination offset (default 0)'),
    },
    async (params) => {
      try {
        if (params.account_id && params.contact_id) {
          return {
            content: [{ type: 'text' as const, text: JSON.stringify({ error: 'invalid_params', message: 'Pass either account_id or contact_id, not both.' }) }],
            isError: true,
          };
        }

        const limit = params.limit ?? 25;
        const offset = params.offset ?? 0;
        const page = Math.floor(offset / limit) + 1;

        const result = await client.listNotes(
          {
            entityId: params.account_id ?? params.contact_id,
            page,
            itemsPerPage: limit,
          },
          { toolName: 'list_notes', toolCategory: 'notes' }
        );

        const notes = (result.notes ?? []).map(formatNote);

        return {
          content: [
            {
              type: 'text' as const,
              text: JSON.stringify({
                notes,
                total: result.total ?? notes.length,
                page,
                limit,
                offset,
              }),
            },
          ],
        };
      } catch (error) {
        if (error instanceof CustifyApiError) {
          return {
            content: [{ type: 'text' as const, text: JSON.stringify({ error: error.code, message: error.message, statusCode: error.statusCode }) }],
            isError: true,
          };
        }
        throw error;
      }
    }
  );
}
